syntax = "proto3";

package az.fitnest.identity;

option java_multiple_files = true;
option java_package = "az.fitnest.identity.grpc";
option java_outer_classname = "IdentityServiceProto";

message CreateGymAdminRequest {
  string name = 1;
  string surname = 2;
  string phone_number = 3;
  string email = 4;
  string password = 5;
}

message CreateGymAdminResponse {
  int64 user_id = 1;
}

message CheckUserExistsRequest {
  string phone_number = 1;
  string email = 2;
}

message CheckUserExistsResponse {
  bool exists = 1;
  string message = 2;
}

service IdentityService {
  rpc CreateGymAdmin(CreateGymAdminRequest) returns (CreateGymAdminResponse);
  rpc CheckUserExists(CheckUserExistsRequest) returns (CheckUserExistsResponse);
}
